#!/usr/bin/env bash

# Run representative Python probes for the foundational TLA+ abstractions.
# Keep this list deliberately small and deterministic; backend-specific suites
# remain documented next to their focused models.

set -euo pipefail

PYTHON_BIN=${PYTHON_BIN:-/tmp/parsl-venv/bin/python}
PARSL_SOURCE=${PARSL_SOURCE:-/tmp/parsl-source}
TEST_CASE_START=${TEST_CASE_START:-1}
TEST_CASE_LIMIT=${TEST_CASE_LIMIT:-0}
CASE_COUNT=0

if [[ ! -x "$PYTHON_BIN" ]]; then
    echo "Unable to locate Python: $PYTHON_BIN" >&2
    exit 2
fi

tests=(
    tests/test_end_to_end_runtime.py
    tests/test_zmq_serialization_runtime.py
    tests/test_zmq_ack_retry_runtime.py
    tests/test_zmq_serialized_ack_runtime.py
    tests/test_zmq_multipart_ack_runtime.py
    tests/test_zmq_result_attempt_runtime.py
    tests/test_function_object_contents_runtime.py
    tests/test_function_global_default_snapshot_runtime.py
    tests/test_function_object_transport_runtime.py
    tests/test_function_decode_failure_runtime.py
    tests/test_callable_argument_alias_runtime.py
    tests/test_python_nested_alias_runtime.py
    tests/test_callable_deserialize_cache_runtime.py
    tests/test_callable_serializer_cache_runtime.py
    tests/test_callable_equal_cache_runtime.py
    tests/test_callable_mutation_cache_runtime.py
    tests/test_serialization_empty_registry_runtime.py
    tests/test_serialization_envelope_malformed_runtime.py
    tests/test_serialization_plugin_cache_runtime.py
    tests/test_serialization_plugin_error_runtime.py
    tests/test_serialization_runtime.py
    tests/test_serialization_frame_count_runtime.py
    tests/test_serializer_header_consistency_runtime.py
    tests/test_task_transport_close_runtime.py
    tests/test_callable_retry_transport_runtime.py
    tests/test_command_receive_failure_runtime.py
    tests/test_command_send_failure_runtime.py
    tests/test_command_client_close_runtime.py
    tests/test_command_client_concurrent_close_runtime.py
    tests/test_command_send_timeout_runtime.py
    tests/test_command_lock_timeout_runtime.py
    tests/test_command_max_retries_runtime.py
    tests/test_worker_pool_control_frame_runtime.py
    tests/test_htex_worker_poll_priority_runtime.py
    tests/test_htex_poll_priority_future_timeout_runtime.py
    tests/test_join_exception_identity_runtime.py
    tests/test_workqueue_file_cache_identity_runtime.py
    tests/test_function_environment_cache_identity_runtime.py
    tests/test_join_duplicate_object_identity_runtime.py
    tests/test_htex_result_task_id_shape_runtime.py
    tests/test_htex_monitoring_batch_continuation_runtime.py
    tests/test_htex_result_batch_continuation_runtime.py
    tests/test_htex_manager_eligibility_runtime.py
    tests/test_htex_manager_selection_runtime.py
    tests/test_htex_manager_message_runtime.py
    tests/test_pool_executor_callable_cache_runtime.py
    tests/test_results_incoming_close_race_runtime.py
    tests/test_workqueue_malformed_report_runtime.py
    tests/test_taskvine_malformed_report_runtime.py
    tests/test_workqueue_start_timeout_cleanup_runtime.py
    tests/test_file_bytes_transfer_runtime.py
    tests/test_content_file_pipeline_runtime.py
    tests/test_data_manager_stage_in_ordering_runtime.py
    tests/test_data_manager_stage_out_ordering_runtime.py
    tests/test_http_content_length_runtime.py
    tests/test_http_separate_status_readiness_runtime.py
    tests/test_rsync_quoting_runtime.py
    tests/test_file_clean_copy_runtime.py
    tests/test_filesystem_radio_runtime.py
    tests/test_http_staging_runtime.py
    tests/test_http_in_task_transfer_gate_runtime.py
    tests/test_http_in_task_admission_runtime.py
    tests/test_http_in_task_cleanup_gate_runtime.py
    tests/test_htex_heartbeat_runtime.py
    tests/test_heartbeat_result_attempt_runtime.py
    tests/test_heartbeat_clock_jump_runtime.py
    tests/test_htex_contact_timeout_starvation_runtime.py
    tests/test_periodic_timer_runtime.py
    tests/test_htex_shutdown_timeout_runtime.py
    tests/test_htex_address_probe_timeout_runtime.py
    tests/test_htex_worker_drain_clock_runtime.py
    tests/test_worker_pool_heartbeat_runtime.py
    tests/test_heartbeat_parameter_validation_runtime.py
    tests/test_worker_contact_clock_rollback_runtime.py
    tests/test_provider_poll_clock_runtime.py
    tests/test_provider_poll_clock_rollback_runtime.py
    tests/test_resource_monitor_clock_runtime.py
    tests/test_monitoring_batch_clock_runtime.py
    tests/test_monitoring_zmq_batch_clock_runtime.py
    tests/test_monitoring_queue_fairness_runtime.py
    tests/test_stageout_failure_gate_runtime.py
    tests/test_join_immediate_mutation_runtime.py
    tests/test_staging_predicate_failure_runtime.py
    tests/test_data_ready_stageout_failure_runtime.py
    tests/test_bad_state_submit_race_runtime.py
    tests/test_worker_initial_probe_timeout_runtime.py
    tests/test_time_limited_open_timeout_runtime.py
    tests/test_bash_timeout_cleanup_runtime.py
    tests/test_python_timeout_parameter_runtime.py
    tests/test_timer_close_timeout_runtime.py
    tests/test_retry_timeout_runtime.py
    tests/test_timeout_timer_runtime.py
    tests/test_monitoring_db_runtime.py
    tests/test_monitoring_resource_history_runtime.py
    tests/test_monitoring_batch_atomicity_runtime.py
    tests/test_monitoring_malformed_continuation_runtime.py
    tests/test_monitoring_persistent_retry_runtime.py
    tests/test_join_runtime.py
    tests/test_join_monitoring_runtime.py
    tests/test_join_multi_output_monitoring_runtime.py
    tests/test_join_retry_runtime.py
    tests/test_nested_join_retry_runtime.py
    tests/test_dependency_traversal_runtime.py
    tests/test_future_cancellation_runtime.py
    tests/test_future_projection_runtime.py
    tests/test_future_projection_retry_runtime.py
    tests/test_future_projection_retry_monitoring_runtime.py
    tests/test_future_projection_retry_zmq_runtime.py
    tests/test_future_wait_timeout_runtime.py
    tests/test_join_cancellation_end_to_end_runtime.py
    tests/test_join_duplicate_cancellation_runtime.py
    tests/test_join_list_cancellation_end_to_end_runtime.py
    tests/test_join_list_cancellation_runtime.py
    tests/test_join_single_cancellation_runtime.py
    tests/test_join_failure_aggregation_runtime.py
    tests/test_join_duplicate_failure_aggregation_runtime.py
    tests/test_join_cleanup_lifecycle_runtime.py
    tests/test_join_return_shape_runtime.py
    tests/test_join_zmq_retry_runtime.py
    tests/test_join_heartbeat_retry_runtime.py
    tests/test_join_return_equality_runtime.py
    tests/test_outer_join_cancellation_runtime.py
    tests/test_join_body_retry_runtime.py
    tests/test_join_callback_runtime.py
    tests/test_join_none_result_runtime.py
    tests/test_nested_join_runtime.py
    tests/test_join_three_list_runtime.py
    tests/test_join_callable_transport_runtime.py
    tests/test_join_error_root_cause_runtime.py
    tests/test_join_list_mutation_runtime.py
    tests/test_join_retry_duplicates_runtime.py
    tests/test_provider_worker_scaling_runtime.py
    tests/test_poller_executor_isolation_runtime.py
    tests/test_executor_selection_runtime.py
    tests/test_thread_executor_future_lifecycle_runtime.py
    tests/test_thread_executor_empty_resource_spec_runtime.py
    tests/test_flux_serialization_error_name_runtime.py
    tests/test_flux_serialization_failure_runtime.py
    tests/test_workqueue_submit_runtime.py
    tests/test_taskvine_submit_runtime.py
    tests/test_workqueue_cancelled_result_runtime.py
    tests/test_taskvine_cancelled_result_runtime.py
    tests/test_flux_result_runtime.py
    tests/test_flux_result_file_cancellation_runtime.py
    tests/test_scale_in_result_shape_runtime.py
    tests/test_flux_submission_failure_runtime.py
    tests/test_globus_compute_result_runtime.py
    tests/test_radical_results_runtime.py
    tests/test_radical_late_callback_runtime.py
    tests/test_mpi_backlog_retry_runtime.py
    tests/test_mpi_malformed_result_runtime.py
    tests/test_mpi_no_resource_result_monitoring_runtime.py
    tests/test_block_provider_bad_state_monitoring_runtime.py
    tests/test_executor_context_exit_runtime.py
    tests/test_monitoring_wrapper_cleanup_runtime.py
    tests/test_taskvine_factory_runtime.py
    tests/test_taskvine_start_failure_cleanup_runtime.py
    tests/test_taskvine_failure_fanout_runtime.py
    tests/test_workqueue_shutdown_runtime.py
    tests/test_thread_executor_future_lifecycle_runtime.py
    tests/test_aws_submit_runtime.py
    tests/test_azure_submit_runtime.py
    tests/test_googlecloud_submit_runtime.py
    tests/test_htex_cancelled_result_runtime.py
    tests/test_htex_result_queue_runtime.py
    tests/test_remote_exception_transport_runtime.py
    tests/test_htex_manager_loss_runtime.py
    tests/test_htex_cores_per_worker_runtime.py
    tests/test_htex_force_scale_in_runtime.py
    tests/test_htex_negative_scale_in_runtime.py
    tests/test_htex_scale_in_race_runtime.py
    tests/test_scale_out_failure_monitoring_runtime.py
    tests/test_htex_shutdown_reap_runtime.py
    tests/test_htex_unknown_manager_runtime.py
    tests/test_htex_unknown_result_type_runtime.py
    tests/test_htex_unknown_task_result_runtime.py
    tests/test_htex_worker_capacity_runtime.py
    tests/test_htex_executor_result_frame_continuation_runtime.py
    tests/test_htex_result_message_malformed_runtime.py
    tests/test_htex_worker_task_batch_shape_runtime.py
    tests/test_htex_worker_task_frame_continuation_runtime.py
    tests/test_htex_manager_message_runtime.py
    tests/test_htex_manager_selection_runtime.py
    tests/test_htex_task_context_type_runtime.py
    tests/test_htex_task_id_type_runtime.py
    tests/test_htex_task_message_malformed_runtime.py
    tests/test_htex_task_ingress_continuation_runtime.py
    tests/test_htex_serialization_failure_runtime.py
    tests/test_htex_serialization_error_name_runtime.py
    tests/test_htex_result_decode_continuation_runtime.py
    tests/test_htex_result_decode_failure_runtime.py
    tests/test_result_decode_retry_monitoring_runtime.py
    tests/test_htex_result_forwarding_runtime.py
    tests/test_htex_ferry_result_send_failure_runtime.py
    tests/test_htex_task_dispatch_send_failure_runtime.py
    tests/test_htex_command_ingress_isolation_runtime.py
    tests/test_htex_command_reply_send_failure_runtime.py
    tests/test_htex_monitoring_message_runtime.py
    tests/test_execute_wait_timeout_runtime.py
    tests/test_negative_scale_in_runtime.py
    tests/test_flux_cancel_submit_race_runtime.py
    tests/test_flux_cancel_underlying_state_runtime.py
    tests/test_globus_compute_submit_race_runtime.py
    tests/test_htex_cancellation_admission_runtime.py
    tests/test_local_pid_admission_runtime.py
    tests/test_poller_close_scale_in_runtime.py
    tests/test_poller_duplicate_executor_runtime.py
    tests/test_scale_in_cancel_shape_runtime.py
    tests/test_aws_cancel_runtime.py
    tests/test_azure_status_runtime.py
    tests/test_condor_submit_runtime.py
    tests/test_flux_inflight_submission_failure_runtime.py
    tests/test_googlecloud_status_runtime.py
    tests/test_grid_engine_status_batch_runtime.py
    tests/test_lsf_status_runtime.py
    tests/test_pbspro_status_runtime.py
    tests/test_slurm_status_batch_runtime.py
    tests/test_globus_compute_resource_spec_type_runtime.py
    tests/test_globus_compute_runtime.py
    tests/test_globus_compute_shutdown_cleanup_runtime.py
    tests/test_globus_compute_restore_failure_runtime.py
    tests/test_globus_staging_runtime.py
    tests/test_globus_transfer_failure_runtime.py
    tests/test_rsync_staging_runtime.py
    tests/test_serialization_fallback_runtime.py
    tests/test_serialization_plugin_failure_cache_runtime.py
    tests/test_curvezmq_certificate_runtime.py
    tests/test_monitoring_zmq_router_failure_runtime.py
    tests/test_monitoring_close_runtime.py
    tests/test_monitoring_starter_construction_failure_runtime.py
    tests/test_monitoring_threshold_runtime.py
    tests/test_monitoring_udp_pickle_runtime.py
    tests/test_monitoring_workflow_duration_runtime.py
    tests/test_htex_ambiguous_result_runtime.py
    tests/test_htex_duplicate_registration_runtime.py
    tests/test_htex_manager_drain_runtime.py
    tests/test_htex_submit_counter_race_runtime.py
    tests/test_htex_watchdog_result_race_runtime.py
    tests/test_htex_worker_watchdog_runtime.py
    tests/test_thread_executor_runtime.py
    tests/test_thread_executor_lifecycle_runtime.py
    tests/test_flux_shutdown_lifecycle_runtime.py
    tests/test_radical_decode_failure_runtime.py
    tests/test_radical_decode_monitoring_runtime.py
    tests/test_radical_master_submit_shape_runtime.py
    tests/test_radical_master_count_admission_runtime.py
    tests/test_thread_executor_resource_spec_runtime.py
    tests/test_thread_executor_thread_count_runtime.py
    tests/test_pool_executor_map_runtime.py
    tests/test_task_transport_runtime.py
    tests/test_workqueue_duplicate_report_runtime.py
    tests/test_taskvine_duplicate_report_runtime.py
    tests/test_cluster_provider_unknown_job_runtime.py
    tests/test_grid_engine_duplicate_status_runtime.py
    tests/test_lsf_duplicate_status_runtime.py
    tests/test_slurm_duplicate_status_runtime.py
    tests/test_torque_duplicate_status_runtime.py
    tests/test_grid_engine_cancel_runtime.py
    tests/test_lsf_missing_job_runtime.py
    tests/test_torque_cancel_runtime.py
    tests/test_radical_unknown_callback_runtime.py
    tests/test_block_provider_bad_state_runtime.py
    tests/test_block_provider_bad_state_order_runtime.py
    tests/test_block_provider_bad_state_mutation_runtime.py
    tests/test_strategy_runtime.py
    tests/test_strategy_idle_clock_runtime.py
    tests/test_memoization_runtime.py
    tests/test_memo_closure_runtime.py
    tests/test_memo_dict_ordering_runtime.py
    tests/test_memo_ignore_key_runtime.py
    tests/test_serializer_registry_runtime.py
    tests/test_python_cyclic_object_runtime.py
    tests/test_taskvine_results_runtime.py
    tests/test_workqueue_failure_fanout_runtime.py
    tests/test_workqueue_results_runtime.py
    tests/test_file_path_runtime.py
    tests/test_command_client_runtime.py
    tests/test_command_deadline_runtime.py
    tests/test_timer_interval_validation_runtime.py
    tests/test_walltime_parsing_runtime.py
    tests/test_tasks_outgoing_runtime.py
    tests/test_tasks_outgoing_close_runtime.py
    tests/test_results_incoming_runtime.py
    tests/test_execute_task_runtime.py
    tests/test_grid_engine_submit_runtime.py
    tests/test_lsf_submit_runtime.py
    tests/test_lsf_submit_job_id_runtime.py
    tests/test_pbspro_submit_runtime.py
    tests/test_slurm_submit_runtime.py
    tests/test_torque_submit_runtime.py
    tests/test_torque_submit_shape_runtime.py
    tests/test_taskvine_shutdown_runtime.py
    tests/test_taskvine_resource_spec_shape_runtime.py
    tests/test_workqueue_resource_spec_shape_runtime.py
    tests/test_radical_failure_fanout_runtime.py
    tests/test_dependency_runtime.py
    tests/test_input_dependency_duplicate_runtime.py
    tests/test_apply_dispatch_boundary_runtime.py
    tests/test_retry_handler_runtime.py
    tests/test_duplicate_job_id_runtime.py
    tests/test_bad_state_task_mutation_runtime.py
    tests/test_grid_engine_status_runtime.py
    tests/test_lsf_cancel_runtime.py
    tests/test_lsf_resource_validation_runtime.py
    tests/test_pbspro_job_id_alias_runtime.py
    tests/test_slurm_foreign_job_runtime.py
    tests/test_torque_tasks_per_node_runtime.py
    tests/test_local_submit_pid_shape_runtime.py
    tests/test_local_tasks_per_node_runtime.py
    tests/test_bash_app_outcome_runtime.py
    tests/test_cluster_submit_script_runtime.py
    tests/test_job_status_output_read_error_runtime.py
    tests/test_job_status_output_summary_runtime.py
    tests/test_mpi_no_resource_result_runtime.py
    tests/test_mpi_nonpositive_resource_runtime.py
    tests/test_mpi_prefix_runtime.py
    tests/test_mpi_spec_runtime.py
    tests/test_mpi_task_context_shape_runtime.py
    tests/test_probe_addresses_runtime.py
    tests/test_radical_bulk_shutdown_runtime.py
    tests/test_timer_reentrant_close_runtime.py
    tests/test_local_provider_cancel_unknown_runtime.py
    tests/test_htex_submit_runtime.py
    tests/test_kubernetes_cancel_runtime.py
    tests/test_kubernetes_submit_runtime.py
    tests/test_azure_cancel_runtime.py
    tests/test_googlecloud_cancel_runtime.py
    tests/test_condor_cancel_runtime.py
    tests/test_condor_empty_submit_runtime.py
    tests/test_flux_error_cleanup_cancellation_runtime.py
    tests/test_flux_provider_status_empty_runtime.py
    tests/test_flux_working_directory_runtime.py
    tests/test_local_provider_submit_cleanup_runtime.py
    tests/test_staging_provider_dispatch_runtime.py
    tests/test_staging_provider_transfer_failure_runtime.py
    tests/test_htex_task_priority_type_runtime.py
    tests/test_htex_task_resource_spec_type_runtime.py
    tests/test_htex_version_mismatch_runtime.py
    tests/test_monitoring_hub_close_runtime.py
    tests/test_monitoring_hub_close_before_start_runtime.py
    tests/test_monitoring_hub_start_failure_cleanup_runtime.py
    tests/test_monitoring_hub_repeated_start_runtime.py
    tests/test_monitoring_close_idempotence_runtime.py
    tests/test_monitoring_shutdown_drain_runtime.py
    tests/test_monitoring_remote_lifecycle_runtime.py
    tests/test_monitoring_shutdown_race_runtime.py
    tests/test_monitoring_dispatch_envelope_runtime.py
    tests/test_monitoring_malformed_worker_message_runtime.py
    tests/test_monitoring_status_history_runtime.py
    tests/test_monitoring_zmq_tuple_shape_runtime.py
    tests/test_result_monitoring_attempt_runtime.py
    tests/test_provider_executor_timed_monitoring_runtime.py
    tests/test_poller_executor_future_isolation_runtime.py
    tests/test_zmq_serialized_ack_future_monitoring_runtime.py
    tests/test_heartbeat_timeout_future_monitoring_runtime.py
    tests/test_join_timed_monitoring_runtime.py
    tests/test_join_retry_stale_result_runtime.py
    tests/test_zip_duplicate_readiness_runtime.py
    tests/test_aws_unknown_future_monitoring_runtime.py
    tests/test_condor_empty_submit_future_monitoring_runtime.py
    tests/test_pbspro_malformed_future_monitoring_runtime.py
    tests/test_monitoring_batch_runtime.py
    tests/test_monitoring_db_permanent_error_runtime.py
    tests/test_monitoring_db_update_permanent_error_runtime.py
    tests/test_monitoring_deferred_runtime.py
    tests/test_monitoring_worker_status_atomicity_runtime.py
    tests/test_monitoring_worker_try_atomicity_runtime.py
    tests/test_monitoring_internal_queue_drain_runtime.py
    tests/test_monitoring_external_queue_empty_runtime.py
    tests/test_monitoring_udp_drain_clock_runtime.py
    tests/test_monitoring_deferred_multiplicity_runtime.py
    tests/test_monitoring_task_try_worker_lifecycle_runtime.py
    tests/test_monitoring_last_message_runtime.py
    tests/test_monitoring_task_insert_bookkeeping_runtime.py
    tests/test_monitoring_try_insert_bookkeeping_runtime.py
    tests/test_monitoring_workflow_insert_bookkeeping_runtime.py
    tests/test_monitoring_workflow_end_bookkeeping_runtime.py
    tests/test_monitoring_foreign_key_runtime.py
    tests/test_monitoring_update_persistent_retry_runtime.py
    tests/test_ftp_connection_cleanup_runtime.py
    tests/test_ftp_partial_cleanup_runtime.py
    tests/test_ftp_in_task_transfer_gate_runtime.py
    tests/test_ftp_staging_runtime.py
    tests/test_globus_endpoint_path_runtime.py
    tests/test_globus_failure_event_runtime.py
    tests/test_globus_token_schema_runtime.py
    tests/test_globus_init_race_runtime.py
    tests/test_globus_token_file_atomicity_runtime.py
    tests/test_globus_transfer_timeout_runtime.py
    tests/test_http_connection_cleanup_runtime.py
    tests/test_http_partial_cleanup_runtime.py
    tests/test_http_status_validation_runtime.py
    tests/test_rsync_partial_cleanup_runtime.py
    tests/test_rsync_stageout_version_runtime.py
    tests/test_http_existing_destination_runtime.py
    tests/test_http_separate_content_length_runtime.py
    tests/test_http_separate_status_runtime.py
    tests/test_zip_file_transfer_runtime.py
    tests/test_zip_path_validation_runtime.py
    tests/test_zip_traversal_runtime.py
    tests/test_multi_output_stageout_runtime.py
    tests/test_kubernetes_polling_runtime.py
    tests/test_kubernetes_cancel_poll_race_runtime.py
    tests/test_kubernetes_cancel_unknown_runtime.py
    tests/test_condor_chunk_size_runtime.py
    tests/test_condor_status_failure_runtime.py
    tests/test_condor_unknown_job_runtime.py
    tests/test_cluster_status_request_runtime.py
    tests/test_cluster_status_unknown_runtime.py
    tests/test_slurm_batch_strict_runtime.py
    tests/test_slurm_duplicate_status_runtime.py
    tests/test_slurm_empty_job_id_runtime.py
    tests/test_slurm_cancel_runtime.py
    tests/test_slurm_cancel_scale_in_monitoring_runtime.py
    tests/test_slurm_tasks_per_node_runtime.py
    tests/test_condor_status_unknown_runtime.py
    tests/test_grid_engine_empty_submit_runtime.py
    tests/test_grid_engine_missing_status_runtime.py
    tests/test_grid_engine_submit_shape_runtime.py
    tests/test_pbspro_submit_shape_runtime.py
    tests/test_torque_duplicate_status_runtime.py
    tests/test_torque_malformed_status_runtime.py
    tests/test_torque_missing_status_runtime.py
    tests/test_torque_status_failure_runtime.py
    tests/test_lsf_duplicate_status_runtime.py
    tests/test_aws_unknown_instance_runtime.py
    tests/test_aws_status_missing_result_runtime.py
    tests/test_local_provider_runtime.py
    tests/test_local_provider_status_scope_runtime.py
    tests/test_local_provider_exit_status_runtime.py
    tests/test_aws_status_runtime.py
    tests/test_aws_status_reservation_shape_runtime.py
    tests/test_azure_status_bookkeeping_runtime.py
    tests/test_condor_malformed_status_line_runtime.py
    tests/test_slurm_malformed_line_runtime.py
    tests/test_pbspro_malformed_json_runtime.py
    tests/test_kubernetes_unknown_job_runtime.py
    tests/test_aws_status_response_shape_runtime.py
    tests/test_aws_instance_state_runtime.py
    tests/test_aws_state_file_atomicity_runtime.py
    tests/test_aws_teardown_state_cleanup_runtime.py
    tests/test_local_unknown_job_status_runtime.py
    tests/test_local_cancel_failure_runtime.py
    tests/test_local_exit_file_missing_runtime.py
    tests/test_provider_status_shape_runtime.py
    tests/test_torque_cancel_unknown_runtime.py
    tests/test_azure_cancel_bookkeeping_runtime.py
    tests/test_pbspro_status_shape_runtime.py
    tests/test_pbspro_status_batch_isolation_runtime.py
    tests/test_azure_status_ordering_runtime.py
    tests/test_azure_status_remote_failure_runtime.py
    tests/test_googlecloud_status_remote_failure_runtime.py
    tests/test_googlecloud_zone_selection_runtime.py
    tests/test_htex_worker_restart_failure_runtime.py
    tests/test_pbspro_missing_status_runtime.py
    tests/test_mpi_nondivisible_runtime.py
    tests/test_datafuture_runtime.py
    tests/test_datafuture_cancellation_runtime.py
    tests/test_datafuture_falsey_exception_runtime.py
    tests/test_input_list_mutation_runtime.py
    tests/test_output_list_mutation_runtime.py
    tests/test_app_future_output_streams_runtime.py
    tests/test_data_manager_stage_out_return_runtime.py
    tests/test_join_stageout_cancellation_runtime.py
    tests/test_zip_staging_dependency_runtime.py
    tests/test_apply_message_arity_runtime.py
    tests/test_serialization_short_frame_count_runtime.py
    tests/test_serialization_truncated_length_runtime.py
    tests/test_serialization_negative_length_runtime.py
    tests/test_serialization_binary_payload_runtime.py
    tests/test_serialized_result_file_runtime.py
    tests/test_dataflow_cleanup_runtime.py
    tests/test_dataflow_wait_snapshot_runtime.py
    tests/test_retry_handler_negative_cost_runtime.py
    tests/test_retry_handler_non_numeric_cost_runtime.py
    tests/test_memo_function_identity_runtime.py
    tests/test_memo_ignore_outputs_runtime.py
    tests/test_memo_checkpoint_order_runtime.py
    tests/test_memo_checkpoint_result_failure_runtime.py
    tests/test_memo_exception_checkpoint_runtime.py
    tests/test_join_memo_failure_runtime.py
    tests/test_monitoring_db_retry_future_runtime.py
    tests/test_last_checkpoint_uuid_runtime.py
    tests/test_task_status_future_ordering_runtime.py
)

for test_file in "${tests[@]}"; do
    CASE_COUNT=$((CASE_COUNT + 1))
    if [[ "$CASE_COUNT" -lt "$TEST_CASE_START" ]]; then
        continue
    fi
    if [[ "$TEST_CASE_LIMIT" -gt 0 && "$CASE_COUNT" -gt "$TEST_CASE_LIMIT" ]]; then
        break
    fi
    echo "RUN [$CASE_COUNT/${#tests[@]}] $test_file"
    PYTHONPATH="$PARSL_SOURCE${PYTHONPATH:+:$PYTHONPATH}" \
        "$PYTHON_BIN" -m unittest "$test_file" -v
done

echo "Foundational Python runtime smoke suite passed."
